"""Build a fully self-contained Kaggle ConnectX submission file.

The trained weights are embedded directly in the output file as a base64 string
(no external dataset, no project imports), so the single file can be submitted
as-is. Inference is a pure forward pass — the project's no-search constraint.

    python scripts/make_submission.py                              # PPO  -> submissions/ppo.py
    python scripts/make_submission.py --ckpt checkpoints/grpo_s0.pt \\
        --out submissions/grpo.py --method GRPO
"""
from __future__ import annotations

import argparse
import base64
import io
import os
import textwrap

import torch

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def encode_state_dict(ckpt_path: str) -> str:
    """Load a checkpoint, drop the value head, return base64(torch.save(state_dict))."""
    d = torch.load(ckpt_path, map_location="cpu", weights_only=True)
    sd = {k: v for k, v in d["state_dict"].items() if not k.startswith("value.")}
    buf = io.BytesIO()
    torch.save(sd, buf)
    return base64.b64encode(buf.getvalue()).decode("ascii")


def wrap_b64(blob: str, width: int = 100) -> str:
    return "\n".join(f'    "{ln}"' for ln in textwrap.wrap(blob, width))


TEMPLATE = '''\
"""Kaggle ConnectX agent — {method} self-play policy, fully self-contained.

The trained weights are embedded below as base64, so this single file needs
nothing else. Inference is one forward pass over the 3-channel canonical board
(own / opponent / empty); the best legal column is played. No search.

Submit either way:
  * CLI:      kaggle competitions submit -c connectx -f {out_name} -m "{method}"
  * Notebook: paste into a cell prefixed with `%%writefile submission.py`, run,
              then click "Submit to Competition".

Generated by scripts/make_submission.py from {ckpt}.
"""
import base64
import io

import numpy as np
import torch
import torch.nn as nn

ROWS, COLS = 6, 7


# --- network (identical architecture to training) ---------------------------
def _groups(c):
    return max(1, int(np.gcd(8, c)))


class ResidualBlock(nn.Module):
    def __init__(self, c):
        super().__init__()
        g = _groups(c)
        self.conv1 = nn.Conv2d(c, c, 3, padding=1)
        self.gn1 = nn.GroupNorm(g, c)
        self.conv2 = nn.Conv2d(c, c, 3, padding=1)
        self.gn2 = nn.GroupNorm(g, c)

    def forward(self, x):
        h = torch.relu(self.gn1(self.conv1(x)))
        h = self.gn2(self.conv2(h))
        return torch.relu(x + h)


class ConvBackbone(nn.Module):
    def __init__(self, channels, hidden, res_blocks):
        super().__init__()
        self.stem = nn.Sequential(nn.Conv2d(3, channels, 3, padding=1), nn.ReLU())
        self.blocks = nn.Sequential(*[ResidualBlock(channels) for _ in range(res_blocks)])
        self.fc = nn.Sequential(nn.Linear(channels * ROWS * COLS, hidden), nn.ReLU())

    def forward(self, x):
        h = self.blocks(self.stem(x))
        return self.fc(h.flatten(1))


class ActorCritic(nn.Module):
    """Shared conv trunk + policy head (value head dropped for play)."""

    def __init__(self, channels, hidden, res_blocks):
        super().__init__()
        self.backbone = ConvBackbone(channels, hidden, res_blocks)
        self.policy = nn.Linear(hidden, COLS)

    def forward(self, x):
        return self.policy(self.backbone(x))


# --- embedded trained weights (base64 of torch.save(state_dict)) ------------
_WEIGHTS_B64 = (
{weights_literal}
)


def _build_net():
    sd = torch.load(io.BytesIO(base64.b64decode(_WEIGHTS_B64)),
                    map_location="cpu", weights_only=True)
    channels = sd["backbone.stem.0.weight"].shape[0]
    hidden = sd["backbone.fc.0.weight"].shape[0]
    res_blocks = 1 + max(int(k.split(".")[2]) for k in sd
                         if k.startswith("backbone.blocks."))
    net = ActorCritic(channels, hidden, res_blocks)
    net.load_state_dict(sd)
    net.eval()
    return net


_NET = _build_net()  # built once at import (well within Kaggle's init timeout)


# --- the agent ---------------------------------------------------------------
def agent(observation, configuration):
    board = np.asarray(observation["board"], dtype=np.int8).reshape(ROWS, COLS)
    mark = observation["mark"]
    obs = np.stack([board == mark, board == 3 - mark, board == 0]).astype(np.float32)
    with torch.no_grad():
        logits = _NET(torch.from_numpy(obs).unsqueeze(0))[0].numpy()
    legal = board[0] == 0  # top-row empty -> column playable
    return int(np.argmax(np.where(legal, logits, -1e9)))
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", default=os.path.join(ROOT, "checkpoints", "ppo_s0.pt"))
    ap.add_argument("--out", default=os.path.join(ROOT, "submissions", "ppo.py"))
    ap.add_argument("--method", default="PPO")
    args = ap.parse_args()

    blob = encode_state_dict(args.ckpt)
    body = TEMPLATE.format(method=args.method,
                           ckpt=os.path.relpath(args.ckpt, ROOT),
                           out_name=os.path.basename(args.out),
                           weights_literal=wrap_b64(blob))
    with open(args.out, "w") as f:
        f.write(body)
    print(f"wrote {args.out}  ({len(blob) / 1024:.0f} KB base64 embedded)")


if __name__ == "__main__":
    main()
